In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

print("Libraries imported successfully!!")

Libraries imported successfully!!

In [3]:
df = pd.read_csv('Preprocessed_StudentPerformanceFactors.csv')
df.head(5)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,1.0,0.0,0,7,73,1.0,1,0,1.0,2.0,0,2,3,0,1.0,2.0,1,67
1,19,64,1.0,2.0,0,8,59,1.0,1,2,2.0,2.0,0,0,4,0,0.0,1.0,0,61
2,24,98,2.0,2.0,1,7,91,2.0,1,2,2.0,2.0,0,1,4,0,2.0,2.0,1,74
3,29,89,1.0,2.0,1,8,98,2.0,1,1,2.0,2.0,0,0,4,0,1.0,1.0,1,71
4,19,92,2.0,2.0,1,6,65,2.0,1,3,2.0,0.0,0,1,4,0,0.0,2.0,0,70

In [4]:
df['Study_Efficiency'] = df['Hours_Studied'] * df['Attendance'] / 100

df['Academic_Engagement'] = (
    df['Attendance'] +
    df['Hours_Studied'] +
    df['Tutoring_Sessions']
) / 3

df['Lifestyle_Score'] = (
    df['Sleep_Hours'] +
    df['Physical_Activity']
) / 2

In [5]:
df.head(5)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Study_Efficiency,Academic_Engagement,Lifestyle_Score
0,23,84,1.0,0.0,0,7,73,1.0,1,0,...,2,3,0,1.0,2.0,1,67,19.32,35.666667,5.0
1,19,64,1.0,2.0,0,8,59,1.0,1,2,...,0,4,0,0.0,1.0,0,61,12.16,28.333333,6.0
2,24,98,2.0,2.0,1,7,91,2.0,1,2,...,1,4,0,2.0,2.0,1,74,23.52,41.333333,5.5
3,29,89,1.0,2.0,1,8,98,2.0,1,1,...,0,4,0,1.0,1.0,1,71,25.81,39.666667,6.0
4,19,92,2.0,2.0,1,6,65,2.0,1,3,...,1,4,0,0.0,2.0,0,70,17.48,38.000000,5.0

In [8]:


scaler = StandardScaler()

num_cols = [
    'Hours_Studied',
    'Attendance',
    'Previous_Scores',
    'Tutoring_Sessions',
    'Sleep_Hours',
    'Physical_Activity',
    'Study_Efficiency',
    'Academic_Engagement',
    'Lifestyle_Score'
]

df[num_cols] = scaler.fit_transform(df[num_cols])

In [9]:
df.head(5)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Study_Efficiency,Academic_Engagement,Lifestyle_Score
0,0.504942,0.348375,1.0,0.0,0,-0.019796,-0.143800,1.0,1,-1.213934,...,2,0.031411,0,1.0,2.0,1,67,0.627550,0.426504,0.001856
1,-0.162822,-1.383736,1.0,2.0,0,0.661399,-1.116110,1.0,1,0.411451,...,0,1.001199,0,0.0,1.0,0,61,-0.713283,-1.263077,1.116901
2,0.671882,1.560853,2.0,2.0,1,-0.019796,1.106313,2.0,1,0.411451,...,1,1.001199,0,2.0,2.0,1,74,1.414073,1.732090,0.559379
3,1.506587,0.781403,1.0,2.0,1,0.661399,1.592469,2.0,1,-0.401242,...,0,1.001199,0,1.0,1.0,1,71,1.842914,1.348095,1.116901
4,-0.162822,1.041220,2.0,2.0,1,-0.700990,-0.699406,2.0,1,1.224144,...,1,1.001199,0,0.0,2.0,0,70,0.282978,0.964099,0.001856

In [10]:
df.to_csv('Feature_Engineered_StudentPerformanceFactors.csv', index=False)