In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

print("Libraries imported successfully")

Libraries imported successfully

In [4]:
df = pd.read_csv('Cleaned_StudentPerformanceFactors.csv')
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

Hours_studied
Attendence
access_to_resources
extracurricular_activities
previous_score
motivation_level
internet_access
tuttring_sessions
teacher_quality
physical_health
learning_disabilities


Exam_score

In [11]:


for col in df.select_dtypes(exclude=['number']).columns:
    print(f"Unique values in {col}:")
    print(df[col].unique())
    print("----------------------------")

Unique values in Parental_Involvement:
<ArrowStringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str
----------------------------
Unique values in Access_to_Resources:
<ArrowStringArray>
['High', 'Medium', 'Low']
Length: 3, dtype: str
----------------------------
Unique values in Extracurricular_Activities:
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
----------------------------
Unique values in Motivation_Level:
<ArrowStringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str
----------------------------
Unique values in Internet_Access:
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
----------------------------
Unique values in Family_Income:
<ArrowStringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str
----------------------------
Unique values in Teacher_Quality:
<ArrowStringArray>
['Medium', 'High', 'Low']
Length: 3, dtype: str
----------------------------
Unique values in School_Type:
<ArrowStringArray>
['Public', 'Private']
Length: 2, dtype: str
----------------------------
Unique values in Peer_Influence:
<ArrowStringArray>
['Positive', 'Negative', 'Neutral']
Length: 3, dtype: str
----------------------------
Unique values in Learning_Disabilities:
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
----------------------------
Unique values in Parental_Education_Level:
<ArrowStringArray>
['High School', 'College', 'Postgraduate']
Length: 3, dtype: str
----------------------------
Unique values in Distance_from_Home:
<ArrowStringArray>
['Near', 'Moderate', 'Far']
Length: 3, dtype: str
----------------------------
Unique values in Gender:
<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str
----------------------------

In [14]:
binary_cols = [
    'Extracurricular_Activities',
    'Internet_Access',
    'Learning_Disabilities'
]
le = LabelEncoder()
for col in binary_cols:
    df[col] = le.fit_transform(df[col])

In [15]:
df['Gender'] = le.fit_transform(df['Gender'])

In [18]:


ordinal_cols = [
    'Parental_Involvement',
    'Access_to_Resources',
    'Motivation_Level',
    'Family_Income',
    'Teacher_Quality',
    'Distance_from_Home',
    'Parental_Education_Level'
]

encoder = OrdinalEncoder()

df[ordinal_cols] = encoder.fit_transform(df[ordinal_cols])

In [19]:
df['Peer_Influence'] = df['Peer_Influence'].map({
    'Negative': 0,
    'Neutral': 1,
    'Positive': 2
})

In [20]:
df['School_Type'] = df['School_Type'].map({
    'Public': 0,
    'Private': 1
})

In [22]:
df.nunique()

Hours_Studied                 41
Attendance                    41
Parental_Involvement           3
Access_to_Resources            3
Extracurricular_Activities     2
Sleep_Hours                    7
Previous_Scores               51
Motivation_Level               3
Internet_Access                2
Tutoring_Sessions              9
Family_Income                  3
Teacher_Quality                3
School_Type                    2
Peer_Influence                 3
Physical_Activity              7
Learning_Disabilities          2
Parental_Education_Level       3
Distance_from_Home             3
Gender                         2
Exam_Score                    45
dtype: int64

In [24]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,1.0,0.0,0,7,73,1.0,1,0,1.0,2.0,0,2,3,0,1.0,2.0,1,67
1,19,64,1.0,2.0,0,8,59,1.0,1,2,2.0,2.0,0,0,4,0,0.0,1.0,0,61
2,24,98,2.0,2.0,1,7,91,2.0,1,2,2.0,2.0,0,1,4,0,2.0,2.0,1,74
3,29,89,1.0,2.0,1,8,98,2.0,1,1,2.0,2.0,0,0,4,0,1.0,1.0,1,71
4,19,92,2.0,2.0,1,6,65,2.0,1,3,2.0,0.0,0,1,4,0,0.0,2.0,0,70

# Label Encoding & Ordinal Encoding Mapping

- **Gender**
  - [Female, Male] → [0, 1]

- **Internet_Access**
  - [No, Yes] → [0, 1]

- **Extracurricular_Activities**
  - [No, Yes] → [0, 1]

- **Learning_Disabilities**
  - [No, Yes] → [0, 1]

- **School_Type**
  - [Public, Private] → [0, 1]

- **Motivation_Level**
  - [Low, Medium, High] → [0, 1, 2]

- **Teacher_Quality**
  - [Low, Medium, High] → [0, 1, 2]

- **Family_Income**
  - [Low, Medium, High] → [0, 1, 2]

- **Access_to_Resources**
  - [Low, Medium, High] → [0, 1, 2]

- **Parental_Involvement**
  - [Low, Medium, High] → [0, 1, 2]

- **Distance_from_Home**
  - [Near, Moderate, Far] → [0, 1, 2]

- **Peer_Influence**
  - [Negative, Neutral, Positive] → [0, 1, 2]

- **Parental_Education_Level**
  - [High School, College, Postgraduate] → [0, 1, 2]

## Numerical Features (No Encoding Required)

- Hours_Studied
- Attendance
- Sleep_Hours
- Previous_Scores
- Tutoring_Sessions
- Physical_Activity
- Exam_Score

In [25]:
df.to_csv('Preprocessed_StudentPerformanceFactors.csv', index=False)